/*
 * This file is generated by jOOQ.
*/
package com.instagram.proxy.domain.db.tables.records;


import com.instagram.proxy.domain.db.tables.UserRequests;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRequestsRecord extends UpdatableRecordImpl<UserRequestsRecord> implements Record9<Integer, Integer, Integer, Integer, String, String, String, String, Long> {

    private static final long serialVersionUID = 807206763;

    /**
     * Setter for <code>PUBLIC.USER_REQUESTS.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.USER_REQUESTS.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.USER_REQUESTS.MESSAGE_ID</code>.
     */
    public void setMessageId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.USER_REQUESTS.MESSAGE_ID</code>.
     */
    public Integer getMessageId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>PUBLIC.USER_REQUESTS.CHAT_ID</code>.
     */
    public void setChatId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.USER_REQUESTS.CHAT_ID</code>.
     */
    public Integer getChatId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>PUBLIC.USER_REQUESTS.SENDER_ID</code>.
     */
    public void setSenderId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.USER_REQUESTS.SENDER_ID</code>.
     */
    public Integer getSenderId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>PUBLIC.USER_REQUESTS.FIRST_NAME</code>.
     */
    public void setFirstName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.USER_REQUESTS.FIRST_NAME</code>.
     */
    public String getFirstName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.USER_REQUESTS.LAST_NAME</code>.
     */
    public void setLastName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.USER_REQUESTS.LAST_NAME</code>.
     */
    public String getLastName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PUBLIC.USER_REQUESTS.USER_NAME</code>.
     */
    public void setUserName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.USER_REQUESTS.USER_NAME</code>.
     */
    public String getUserName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>PUBLIC.USER_REQUESTS.MESSAGE_TEXT</code>.
     */
    public void setMessageText(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.USER_REQUESTS.MESSAGE_TEXT</code>.
     */
    public String getMessageText() {
        return (String) get(7);
    }

    /**
     * Setter for <code>PUBLIC.USER_REQUESTS.CREATED_TS</code>.
     */
    public void setCreatedTs(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.USER_REQUESTS.CREATED_TS</code>.
     */
    public Long getCreatedTs() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, Integer, String, String, String, String, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, Integer, String, String, String, String, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserRequests.USER_REQUESTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserRequests.USER_REQUESTS.MESSAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return UserRequests.USER_REQUESTS.CHAT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return UserRequests.USER_REQUESTS.SENDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return UserRequests.USER_REQUESTS.FIRST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return UserRequests.USER_REQUESTS.LAST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return UserRequests.USER_REQUESTS.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return UserRequests.USER_REQUESTS.MESSAGE_TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return UserRequests.USER_REQUESTS.CREATED_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getMessageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getChatId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getSenderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getMessageText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getCreatedTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getMessageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getChatId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getSenderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getMessageText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getCreatedTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRequestsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRequestsRecord value2(Integer value) {
        setMessageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRequestsRecord value3(Integer value) {
        setChatId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRequestsRecord value4(Integer value) {
        setSenderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRequestsRecord value5(String value) {
        setFirstName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRequestsRecord value6(String value) {
        setLastName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRequestsRecord value7(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRequestsRecord value8(String value) {
        setMessageText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRequestsRecord value9(Long value) {
        setCreatedTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRequestsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, String value5, String value6, String value7, String value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRequestsRecord
     */
    public UserRequestsRecord() {
        super(UserRequests.USER_REQUESTS);
    }

    /**
     * Create a detached, initialised UserRequestsRecord
     */
    public UserRequestsRecord(Integer id, Integer messageId, Integer chatId, Integer senderId, String firstName, String lastName, String userName, String messageText, Long createdTs) {
        super(UserRequests.USER_REQUESTS);

        set(0, id);
        set(1, messageId);
        set(2, chatId);
        set(3, senderId);
        set(4, firstName);
        set(5, lastName);
        set(6, userName);
        set(7, messageText);
        set(8, createdTs);
    }
}
