version: '3'
services:
  db:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
  app:
    build: .
    environment:
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_USER: ${POSTGRES_USER}
      DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_NAME: ${TELEGRAM_BOT_NAME}
      INSTAGRAM_LOGIN: ${INSTAGRAM_LOGIN}
      INSTAGRAM_PASSWORD: ${INSTAGRAM_PASSWORD}

#      SECURITY_CORS_ALLOWED_ORIGINS: ${SECURITY_CORS_ALLOWED_ORIGINS}
#      SECURITY_CORS_ADD: ${SECURITY_CORS_ADD}
    links:
      - "db:db"
    ports:
      - "8082:8080"
    depends_on:
      - db