/*
 * This file is generated by jOOQ.
*/
package com.instagram.proxy.domain.db;


import com.instagram.proxy.domain.db.tables.SchemaVersion;
import com.instagram.proxy.domain.db.tables.UserRequests;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 472320530;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.USER_REQUESTS</code>.
     */
    public final UserRequests USER_REQUESTS = com.instagram.proxy.domain.db.tables.UserRequests.USER_REQUESTS;

    /**
     * The table <code>PUBLIC.schema_version</code>.
     */
    public final SchemaVersion SCHEMA_VERSION = com.instagram.proxy.domain.db.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            UserRequests.USER_REQUESTS,
            SchemaVersion.SCHEMA_VERSION);
    }
}
